use_frameworks!

platform :ios, '10.0'

target 'ConvertPod_Example' do
  pod 'ConvertPod', :path => '../'

  target 'ConvertPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
